# Configuration parameters for Release Notes

# (Required) Application name: mysql, postgresql, pgbouncer, mysql-router
app: pgbouncer

# (Required) Substrate: vm, k8s
substrate: k8s

# (Required) Old revision to compare (usually previous stable)
last_revision: 229

# (Required) Revisions for each arch/base
amd_22_04: 269
amd_20_04: 
arm_22_04: 268
arm_20_04: 
