# Configuration parameters for Release Notes

# (Required) Application name: mysql, postgresql, pgbouncer, mysql-router
app: pgbouncer

# (Required) Substrate: vm, k8s
substrate: vm

# (Required) Old revision to compare (usually previous stable)
last_revision: 281

# (Required) Revisions for each arch/base
amd_22_04: 396
amd_20_04: 395
arm_22_04: 397
arm_20_04: 394

# (Optional) Output file for formatted release notes
# Default: {app}-{substrate}-release-notes.md
output_file: ''
